/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.myconf.*;
import org.myconf.dao.*;
import org.myconf.util.*;

public class _downloadpacked__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.myconf.AuthTag _jsp_tag0 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag1 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag2 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag3 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag4 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag5 = null;
    try {
      
//*********************************
//security
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.myconf.AuthTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setModule("admin");
      }

      _jsp_tag0.doStartTag();
      _jsp_tag0.setBodyContent(null);
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//define
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//variable
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      org.myconf.beans.StatusBean status;
      status = (org.myconf.beans.StatusBean) request.getAttribute("status");
      if (status == null) {
        status = new org.myconf.beans.StatusBean();
        request.setAttribute("status", status);
      }
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      org.myconf.beans.SubjectBean subject;
      subject = (org.myconf.beans.SubjectBean) request.getAttribute("subject");
      if (subject == null) {
        subject = new org.myconf.beans.SubjectBean();
        request.setAttribute("subject", subject);
      }
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      java.lang.String sum;
      sum = (java.lang.String) request.getAttribute("sum");
      if (sum == null) {
        sum = new java.lang.String();
        request.setAttribute("sum", sum);
      }
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      java.lang.String zipFile;
      zipFile = (java.lang.String) request.getAttribute("zipFile");
      if (zipFile == null) {
        zipFile = new java.lang.String();
        request.setAttribute("zipFile", zipFile);
      }
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//paper statistics data
int[] stats=PaperDAO.statPaper();

//instruction initial
String statusName=Globals.getMessage("common", "common.text.all");
if(status!=null && StringUtils.isNotEmpty(status.getStatus())){
	statusName=status.getStatus();
}
String subjectName=Globals.getMessage("common", "common.text.all");
if(subject!=null && StringUtils.isNotEmpty(subject.getSubject())){
	subjectName=subject.getSubject();
}
zipFile=Globals.root(request)+Globals.PAPER_ROOT_WEB+"/zip/"+zipFile;

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
//*********************************
//head
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/head.jsp");
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
//*********************************
//top
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/top.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_admin.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/admin/sub/mainmenu1.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      pageContext.include("/admin/sub/leftmenu1.jsp");
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      pageContext.include("/inc/stat.jsp");
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.left.download");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag2.setPage("/admin/download.jsp");
      int _jspEval9 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar10 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar10 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag1.setKey("menu.download.single");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((stats[0]));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_tag1.setKey("menu.download.pack");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      _jsp_tag1.setKey("page.downloadpacked.downloading");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      if (_jsp_tag3 == null) {
        _jsp_tag3 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag3.setPageContext(pageContext);
        _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag3.setBundle("admin");
        _jsp_tag3.setKey("page.downloadpacked.ins");
      }

      _jsp_tag3.setArg0(subjectName);
      _jsp_tag3.setArg1(statusName);
      _jsp_tag3.setArg2(sum);
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      if (_jsp_tag4 == null) {
        _jsp_tag4 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag4.setPageContext(pageContext);
        _jsp_tag4.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag4.setBundle("admin");
        _jsp_tag4.setKey("page.downloadpacked.redownload");
      }

      _jsp_tag4.setArg0(zipFile);
      _jsp_tag4.doStartTag();
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      _jsp_tag1.setKey("page.downloadpacked.back");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      _jsp_tag2.setPage("/admin/downloadpack.jsp");
      int _jspEval31 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar32 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar32 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      if (_jsp_tag5 == null) {
        _jsp_tag5 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag5.setPageContext(pageContext);
        _jsp_tag5.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag5.setKey("common.button.back");
      }

      _jsp_tag5.doStartTag();
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((zipFile));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      
//*********************************
//end content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//**********************************
//footer
//**********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      if (_jsp_tag3 != null)
        _jsp_tag3.release();
      if (_jsp_tag4 != null)
        _jsp_tag4.release();
      if (_jsp_tag5 != null)
        _jsp_tag5.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_downloadpacked__jsp.java", "/myconf/admin/downloadpacked.jsp");
    _caucho_line_map.add(17, 1);
    _caucho_line_map.add(1, 36);
    _caucho_line_map.add(6, 42);
    _caucho_line_map.add(7, 52);
    _caucho_line_map.add(8, 56);
    _caucho_line_map.add(13, 62);
    _caucho_line_map.add(25, 75);
    _caucho_line_map.add(26, 82);
    _caucho_line_map.add(27, 89);
    _caucho_line_map.add(28, 96);
    _caucho_line_map.add(29, 103);
    _caucho_line_map.add(46, 119);
    _caucho_line_map.add(51, 125);
    _caucho_line_map.add(54, 127);
    _caucho_line_map.add(59, 133);
    _caucho_line_map.add(60, 135);
    _caucho_line_map.add(61, 137);
    _caucho_line_map.add(66, 143);
    _caucho_line_map.add(72, 145);
    _caucho_line_map.add(73, 147);
    _caucho_line_map.add(80, 149);
    _caucho_line_map.add(84, 159);
    _caucho_line_map.add(84, 171);
    _caucho_line_map.add(84, 174);
    _caucho_line_map.add(85, 176);
    _caucho_line_map.add(97, 179);
    _caucho_line_map.add(102, 182);
    _caucho_line_map.add(105, 195);
    _caucho_line_map.add(108, 206);
    _caucho_line_map.add(108, 209);
    _caucho_line_map.add(108, 215);
    _caucho_line_map.add(111, 224);
    _caucho_line_map.add(121, 226);
    _caucho_line_map.add(126, 232);
    _caucho_line_map.add(131, 238);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/downloadpacked.jsp"), 1178378636000L, 4881L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string6;
  private static byte []_jsp_string15;
  private static byte []_jsp_string7;
  private static byte []_jsp_string13;
  private static byte []_jsp_string1;
  private static byte []_jsp_string3;
  private static byte []_jsp_string17;
  private static byte []_jsp_string16;
  private static byte []_jsp_string0;
  private static byte []_jsp_string12;
  private static byte []_jsp_string8;
  private static byte []_jsp_string10;
  private static byte []_jsp_string4;
  private static byte []_jsp_string5;
  private static byte []_jsp_string11;
  private static byte []_jsp_string9;
  private static byte []_jsp_string14;
  private static byte []_jsp_string2;
  static {
    try {
      _jsp_string6 = "</b></td>\r\n        </tr>\r\n        <tr> \r\n          <td align=\"right\" class=\"pagecontent_right\">\r\n          	<a href=\"".getBytes("UTF8");
      _jsp_string15 = "</a></td>\r\n                    </tr>\r\n                  </table>\r\n				  <iframe src=\"".getBytes("UTF8");
      _jsp_string7 = "\" class=\"pagemenu\">".getBytes("UTF8");
      _jsp_string13 = "<a href=\"".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n".getBytes("UTF8");
      _jsp_string3 = "\r\n<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"MARGIN-TOP: 10px;\">\r\n  <tr>\r\n    <td width=\"180\" height=\"55\" valign=\"top\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"leftmenu\">\r\n        <tr> \r\n          <td height=\"41\">\r\n			".getBytes("UTF8");
      _jsp_string17 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string16 = "\" width=\"0\" height=\"0\"></iframe>\r\n                  </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n      </table>\r\n    </td>\r\n  </tr>\r\n</table>\r\n".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string12 = "</td>\r\n                    </tr>\r\n                    <tr>\r\n                      <td>".getBytes("UTF8");
      _jsp_string8 = "(".getBytes("UTF8");
      _jsp_string10 = "</span></td>\r\n        </tr>\r\n      </table>\r\n      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr> \r\n          <td> <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n              <tr> \r\n                <td width=\"52%\"> <div class=\"spacer_20\"></div></td>\r\n              </tr>\r\n            </table>\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"3\" cellspacing=\"1\" class=\"table\">\r\n              <tr> \r\n                <td colspan=\"3\" nowrap class=\"table_head\"><strong>".getBytes("UTF8");
      _jsp_string4 = "\r\n			".getBytes("UTF8");
      _jsp_string5 = "\r\n          </td>\r\n        </tr>\r\n      </table></td>\r\n    <td width=\"598\" valign=\"top\" class=\"pagecontent\">\r\n	  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <tr> \r\n          <td class=\"pagecontent_title\"><b>".getBytes("UTF8");
      _jsp_string11 = "</strong></td>\r\n              </tr>\r\n              <tr> \r\n                <td colspan=\"3\" valign=\"top\" class=\"table_cell\"><table width=\"92%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"8\">\r\n                    <tr>\r\n                      <td>".getBytes("UTF8");
      _jsp_string9 = ")</a> \r\n            > <span class=\"pagemenu_visited\">".getBytes("UTF8");
      _jsp_string14 = "\" class=\"blue\">".getBytes("UTF8");
      _jsp_string2 = "\r\n\r\n<body>\r\n".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
