/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.myconf.dao.*;
import org.myconf.beans.*;
import java.util.*;

public class _reviewdate__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.myconf.AuthTag _jsp_tag0 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag1 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag2 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag3 = null;
    try {
      
//*********************************
//security
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.myconf.AuthTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setModule("admin");
      }

      _jsp_tag0.doStartTag();
      _jsp_tag0.setBodyContent(null);
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//define
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//variable
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
int year=Calendar.getInstance().get(Calendar.YEAR)-2;
int syear1=0;
int smonth1=0;
int sday1=0;
int shour1=0;
int syear2=0;
int smonth2=0;
int sday2=0;
int shour2=0;

ConfigBean conf=ConfigDAO.getCurrentConfig(ConfigBean.CONFIG_ID);
if(conf!=null){
	if(conf.getReviewBeginDate()>0){
		Calendar begin=Calendar.getInstance();
		begin.setTimeInMillis(conf.getReviewBeginDate());
		syear1=begin.get(Calendar.YEAR);
		smonth1=begin.get(Calendar.MONTH)+1;
		sday1=begin.get(Calendar.DAY_OF_MONTH);
		shour1=begin.get(Calendar.HOUR_OF_DAY);
	}
	if(conf.getReviewEndDate()>0){
		Calendar end=Calendar.getInstance();
		end.setTimeInMillis(conf.getReviewEndDate());
		syear2=end.get(Calendar.YEAR);
		smonth2=end.get(Calendar.MONTH)+1;
		sday2=end.get(Calendar.DAY_OF_MONTH);
		shour2=end.get(Calendar.HOUR_OF_DAY);
	}
}else{
	conf=new ConfigBean();
}
List refers=ReferDAO.list();
List stats=StatusDAO.list();

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
//*********************************
//head
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/head.jsp");
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
//*********************************
//top
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/top.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_admin.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/admin/sub/mainmenu1.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      pageContext.include("/admin/sub/leftmenu1.jsp");
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      pageContext.include("/inc/stat.jsp");
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.left.review");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag2.setPage("/admin/reviewins.jsp");
      int _jspEval9 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar10 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar10 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag1.setKey("menu.sub.top.reviewins");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_tag2.setPage("/admin/reviewrefer.jsp");
      int _jspEval16 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar17 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar17 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag1.setKey("menu.sub.top.refer");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_tag2.setPage("/admin/reviewstatus.jsp");
      int _jspEval23 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar24 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar24 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag1.setKey("menu.sub.top.status");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_tag1.setKey("menu.sub.top.reviewdate");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      if(refers==null || refers.size()==0 || stats==null || stats.size()==0){
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("page.reviewdate.no");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      }else{
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("page.reviewdate.ins1");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      _jsp_tag1.setKey("page.reviewdate.ins2");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      _jsp_tag1.setKey("page.reviewdate.ins3");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag2.setPage("/config.do");
      int _jspEval45 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar46 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar46 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      _jsp_tag1.setKey("page.reviewdate.attention");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      _jsp_tag1.setKey("page.reviewdate.title.begin");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((syear1));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((syear1));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      for(int i=0;i<8;i++){
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((year+i));
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((year+i));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      }
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      if (_jsp_tag3 == null) {
        _jsp_tag3 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag3.setPageContext(pageContext);
        _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag3.setKey("common.text.year");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((smonth1));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((smonth1));
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      _jsp_tag3.setKey("common.text.month");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((sday1));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((sday1));
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      _jsp_tag3.setKey("common.text.day");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((shour1));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((shour1));
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      _jsp_tag3.setKey("common.text.hour");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string29, 0, _jsp_string29.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("page.reviewdate.title.end");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string30, 0, _jsp_string30.length);
      out.print((syear2));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((syear2));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      for(int i=0;i<8;i++){
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((year));
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((year));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      year++;}
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      if (_jsp_tag3 == null) {
        _jsp_tag3 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag3.setPageContext(pageContext);
        _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag3.setKey("common.text.year");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      out.print((smonth2));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((smonth2));
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      _jsp_tag3.setKey("common.text.month");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((sday2));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((sday2));
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      _jsp_tag3.setKey("common.text.day");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((shour2));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((shour2));
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      _jsp_tag3.setKey("common.text.hour");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((ConfigBean.TRUE));
      pageContext.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((ConfigBean.FALSE));
      pageContext.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((conf.getIsAnony()));
      pageContext.write(_jsp_string37, 0, _jsp_string37.length);
      if(conf.getIsAnony()==ConfigBean.TRUE){out.print("checked");}
      pageContext.write(_jsp_string38, 0, _jsp_string38.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("page.reviewdate.isanony");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string39, 0, _jsp_string39.length);
      if (_jsp_tag3 == null) {
        _jsp_tag3 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag3.setPageContext(pageContext);
        _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag3.setKey("common.button.save");
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      }
      pageContext.write(_jsp_string41, 0, _jsp_string41.length);
      
//*********************************
//end content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//**********************************
//footer
//**********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string42, 0, _jsp_string42.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      if (_jsp_tag3 != null)
        _jsp_tag3.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_reviewdate__jsp.java", "/myconf/admin/reviewdate.jsp");
    _caucho_line_map.add(17, 1);
    _caucho_line_map.add(1, 34);
    _caucho_line_map.add(6, 40);
    _caucho_line_map.add(7, 50);
    _caucho_line_map.add(8, 54);
    _caucho_line_map.add(13, 60);
    _caucho_line_map.add(25, 73);
    _caucho_line_map.add(62, 109);
    _caucho_line_map.add(67, 115);
    _caucho_line_map.add(70, 117);
    _caucho_line_map.add(75, 123);
    _caucho_line_map.add(76, 125);
    _caucho_line_map.add(77, 127);
    _caucho_line_map.add(82, 133);
    _caucho_line_map.add(88, 135);
    _caucho_line_map.add(89, 137);
    _caucho_line_map.add(96, 139);
    _caucho_line_map.add(99, 149);
    _caucho_line_map.add(99, 161);
    _caucho_line_map.add(100, 164);
    _caucho_line_map.add(100, 170);
    _caucho_line_map.add(101, 173);
    _caucho_line_map.add(101, 179);
    _caucho_line_map.add(102, 182);
    _caucho_line_map.add(108, 187);
    _caucho_line_map.add(111, 197);
    _caucho_line_map.add(117, 199);
    _caucho_line_map.add(118, 209);
    _caucho_line_map.add(119, 212);
    _caucho_line_map.add(123, 215);
    _caucho_line_map.add(128, 227);
    _caucho_line_map.add(133, 230);
    _caucho_line_map.add(135, 233);
    _caucho_line_map.add(135, 235);
    _caucho_line_map.add(136, 237);
    _caucho_line_map.add(137, 239);
    _caucho_line_map.add(137, 241);
    _caucho_line_map.add(138, 243);
    _caucho_line_map.add(142, 254);
    _caucho_line_map.add(142, 256);
    _caucho_line_map.add(156, 258);
    _caucho_line_map.add(158, 261);
    _caucho_line_map.add(158, 263);
    _caucho_line_map.add(191, 265);
    _caucho_line_map.add(193, 268);
    _caucho_line_map.add(193, 270);
    _caucho_line_map.add(219, 272);
    _caucho_line_map.add(224, 275);
    _caucho_line_map.add(227, 285);
    _caucho_line_map.add(227, 287);
    _caucho_line_map.add(228, 289);
    _caucho_line_map.add(229, 291);
    _caucho_line_map.add(229, 293);
    _caucho_line_map.add(230, 295);
    _caucho_line_map.add(234, 306);
    _caucho_line_map.add(234, 308);
    _caucho_line_map.add(248, 310);
    _caucho_line_map.add(250, 313);
    _caucho_line_map.add(250, 315);
    _caucho_line_map.add(283, 317);
    _caucho_line_map.add(285, 320);
    _caucho_line_map.add(285, 322);
    _caucho_line_map.add(311, 324);
    _caucho_line_map.add(317, 327);
    _caucho_line_map.add(327, 331);
    _caucho_line_map.add(328, 333);
    _caucho_line_map.add(328, 335);
    _caucho_line_map.add(335, 345);
    _caucho_line_map.add(343, 354);
    _caucho_line_map.add(347, 356);
    _caucho_line_map.add(352, 362);
    _caucho_line_map.add(357, 368);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/reviewdate.jsp"), 1179848050000L, 16682L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string15;
  private static byte []_jsp_string16;
  private static byte []_jsp_string18;
  private static byte []_jsp_string7;
  private static byte []_jsp_string1;
  private static byte []_jsp_string22;
  private static byte []_jsp_string13;
  private static byte []_jsp_string30;
  private static byte []_jsp_string10;
  private static byte []_jsp_string24;
  private static byte []_jsp_string42;
  private static byte []_jsp_string0;
  private static byte []_jsp_string32;
  private static byte []_jsp_string12;
  private static byte []_jsp_string14;
  private static byte []_jsp_string29;
  private static byte []_jsp_string4;
  private static byte []_jsp_string39;
  private static byte []_jsp_string37;
  private static byte []_jsp_string34;
  private static byte []_jsp_string2;
  private static byte []_jsp_string33;
  private static byte []_jsp_string35;
  private static byte []_jsp_string11;
  private static byte []_jsp_string8;
  private static byte []_jsp_string38;
  private static byte []_jsp_string9;
  private static byte []_jsp_string20;
  private static byte []_jsp_string3;
  private static byte []_jsp_string41;
  private static byte []_jsp_string28;
  private static byte []_jsp_string27;
  private static byte []_jsp_string36;
  private static byte []_jsp_string21;
  private static byte []_jsp_string25;
  private static byte []_jsp_string31;
  private static byte []_jsp_string23;
  private static byte []_jsp_string17;
  private static byte []_jsp_string26;
  private static byte []_jsp_string19;
  private static byte []_jsp_string40;
  private static byte []_jsp_string5;
  private static byte []_jsp_string6;
  static {
    try {
      _jsp_string15 = "\" method=\"post\" name=\"sdate\" id=\"sdate\">\r\n              <input name=\"eventSubmit_Save\" type=\"hidden\" id=\"eventSubmit_Save\" value=\"0\">\r\n              <input name=\"fromPage\" type=\"hidden\" id=\"fromPage\" value=\"/admin/reviewdate.jsp\">\r\n              <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n                <tr> \r\n                  <td class=\"form_row_content\">&nbsp;&nbsp;<span class=\"redins\">".getBytes("UTF8");
      _jsp_string16 = "</span></td>\r\n                </tr>\r\n              </table>\r\n              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"form_row\">\r\n                <tr> \r\n                  <td width=\"20%\" class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string18 = "\" selected>".getBytes("UTF8");
      _jsp_string7 = "\" class=\"pagemenu\">".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n".getBytes("UTF8");
      _jsp_string22 = "\r\n                    </select>\r\n                    ".getBytes("UTF8");
      _jsp_string13 = "</li>\r\n                  <li>".getBytes("UTF8");
      _jsp_string30 = "</td>\r\n                  <td class=\"form_row_content\">\r\n					<select name=\"reviewYear2\" id=\"reviewYear2\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string10 = "</span></td>\r\n        </tr>\r\n      </table>\r\n      ".getBytes("UTF8");
      _jsp_string24 = "</option>\r\n                      <option value=\"01\">01</option>\r\n                      <option value=\"02\">02</option>\r\n                      <option value=\"03\">03</option>\r\n                      <option value=\"04\">04</option>\r\n                      <option value=\"05\">05</option>\r\n                      <option value=\"06\">06</option>\r\n                      <option value=\"07\">07</option>\r\n                      <option value=\"08\">08</option>\r\n                      <option value=\"09\">09</option>\r\n                      <option value=\"10\">10</option>\r\n                      <option value=\"11\">11</option>\r\n                      <option value=\"12\">12</option>\r\n                    </select>\r\n                    ".getBytes("UTF8");
      _jsp_string42 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string32 = " \r\n                    <select name=\"reviewDay2\" id=\"reviewDay2\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string12 = "\r\n      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form\">\r\n        <tr>\r\n          <td><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_note\">\r\n              <tr>\r\n                <td><div class=\"spacer_5\"></div>\r\n				  <li>".getBytes("UTF8");
      _jsp_string14 = "</li>\r\n				  <div class=\"spacer_5\"></div></td>\r\n              </tr>\r\n            </table>\r\n            <form action=\"".getBytes("UTF8");
      _jsp_string29 = "</td>\r\n                </tr>\r\n              </table>\r\n              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"form_row\">\r\n                <tr>\r\n                  <td width=\"20%\" class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string4 = "\r\n			".getBytes("UTF8");
      _jsp_string39 = "\r\n					<div class=\"spacer_10\"></div>\r\n					</td>\r\n                </tr>\r\n              </table>\r\n              <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n                <tr> \r\n                  <td class=\"form_row_submit\"><input name=\"save\" type=\"submit\" class=\"button\" id=\"save\" value=\"".getBytes("UTF8");
      _jsp_string37 = "\">\r\n				  	<input name=\"chk\" type=\"checkbox\" onClick=\"check(this)\" id=\"chk\" value=\"1\"".getBytes("UTF8");
      _jsp_string34 = "</td>\r\n                </tr>\r\n              </table>\r\n		      <script language=\"JavaScript\">\r\n				function check(obj){\r\n					if(obj.checked){\r\n						sdate.isAnony.value=".getBytes("UTF8");
      _jsp_string2 = "\r\n\r\n<body>\r\n".getBytes("UTF8");
      _jsp_string33 = " &nbsp; &nbsp; \r\n                    <select name=\"reviewHour2\" id=\"reviewHour2\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string35 = ";\r\n					}else{\r\n						sdate.isAnony.value=".getBytes("UTF8");
      _jsp_string11 = "\r\n      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n        <tr> \r\n          <td height=\"200\" class=\"form_row_content\">&nbsp;&nbsp;<span class=\"redins\">".getBytes("UTF8");
      _jsp_string8 = "</a> \r\n            > <a href=\"".getBytes("UTF8");
      _jsp_string38 = ">".getBytes("UTF8");
      _jsp_string9 = "</a> \r\n            > <span class=\"pagemenu_visited\">".getBytes("UTF8");
      _jsp_string20 = "\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string3 = "\r\n<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"MARGIN-TOP: 10px;\">\r\n  <tr>\r\n    <td width=\"180\" height=\"55\" valign=\"top\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"leftmenu\">\r\n        <tr> \r\n          <td height=\"41\">\r\n			".getBytes("UTF8");
      _jsp_string41 = "\r\n    </td>\r\n  </tr>\r\n</table>\r\n".getBytes("UTF8");
      _jsp_string28 = "</option>\r\n                      <option value=\"00\">00</option>\r\n                      <option value=\"01\">01</option>\r\n                      <option value=\"02\">02</option>\r\n                      <option value=\"03\">03</option>\r\n                      <option value=\"04\">04</option>\r\n                      <option value=\"05\">05</option>\r\n                      <option value=\"06\">06</option>\r\n                      <option value=\"07\">07</option>\r\n                      <option value=\"08\">08</option>\r\n                      <option value=\"09\">09</option>\r\n                      <option value=\"10\">10</option>\r\n                      <option value=\"11\">11</option>\r\n                      <option value=\"12\">12</option>\r\n                      <option value=\"13\">13</option>\r\n                      <option value=\"14\">14</option>\r\n                      <option value=\"15\">15</option>\r\n                      <option value=\"16\">16</option>\r\n                      <option value=\"17\">17</option>\r\n                      <option value=\"18\">18</option>\r\n                      <option value=\"19\">19</option>\r\n                      <option value=\"20\">20</option>\r\n                      <option value=\"21\">21</option>\r\n                      <option value=\"22\">22</option>\r\n                      <option value=\"23\">23</option>\r\n                    </select>\r\n                    ".getBytes("UTF8");
      _jsp_string27 = " &nbsp; &nbsp; \r\n                    <select name=\"reviewHour1\" id=\"reviewHour1\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string36 = ";\r\n					}\r\n				}\r\n			  </script>\r\n              <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n                <tr> \r\n                  <td class=\"form_row_content\">\r\n				  	<div class=\"spacer_5\"></div>\r\n				  	<input name=\"isAnony\" type=\"hidden\" id=\"isAnony\" value=\"".getBytes("UTF8");
      _jsp_string21 = "\">".getBytes("UTF8");
      _jsp_string25 = " \r\n                    <select name=\"reviewDay1\" id=\"reviewDay1\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string31 = " \r\n                    <select name=\"reviewMonth2\" id=\"reviewMonth2\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string23 = " \r\n                    <select name=\"reviewMonth1\" id=\"reviewMonth1\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string17 = "</td>\r\n                  <td class=\"form_row_content\"><select name=\"reviewYear1\" id=\"reviewYear1\">\r\n                      <option value=\"".getBytes("UTF8");
      _jsp_string26 = "</option>\r\n                      <option value=\"01\">01</option>\r\n                      <option value=\"02\">02</option>\r\n                      <option value=\"03\">03</option>\r\n                      <option value=\"04\">04</option>\r\n                      <option value=\"05\">05</option>\r\n                      <option value=\"06\">06</option>\r\n                      <option value=\"07\">07</option>\r\n                      <option value=\"08\">08</option>\r\n                      <option value=\"09\">09</option>\r\n                      <option value=\"10\">10</option>\r\n                      <option value=\"11\">11</option>\r\n                      <option value=\"12\">12</option>\r\n                      <option value=\"13\">13</option>\r\n                      <option value=\"14\">14</option>\r\n                      <option value=\"15\">15</option>\r\n                      <option value=\"16\">16</option>\r\n                      <option value=\"17\">17</option>\r\n                      <option value=\"18\">18</option>\r\n                      <option value=\"19\">18</option>\r\n                      <option value=\"20\">20</option>\r\n                      <option value=\"21\">21</option>\r\n                      <option value=\"22\">22</option>\r\n                      <option value=\"23\">23</option>\r\n                      <option value=\"24\">24</option>\r\n                      <option value=\"25\">25</option>\r\n                      <option value=\"26\">26</option>\r\n                      <option value=\"27\">27</option>\r\n                      <option value=\"28\">28</option>\r\n                      <option value=\"29\">29</option>\r\n                      <option value=\"30\">30</option>\r\n                      <option value=\"31\">31</option>\r\n                    </select>\r\n                    ".getBytes("UTF8");
      _jsp_string19 = "</option>\r\n                      ".getBytes("UTF8");
      _jsp_string40 = "\"> \r\n                  </td>\r\n                </tr>\r\n              </table>\r\n            </form>\r\n		</td>\r\n        </tr>\r\n      </table> \r\n      ".getBytes("UTF8");
      _jsp_string5 = "\r\n          </td>\r\n        </tr>\r\n      </table></td>\r\n    <td width=\"598\" valign=\"top\" class=\"pagecontent\">\r\n	  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <tr>\r\n          <td class=\"pagecontent_title\"><b>".getBytes("UTF8");
      _jsp_string6 = "</b></td>\r\n        </tr>\r\n        <tr>\r\n          <td align=\"right\" class=\"pagecontent_right\"><a href=\"".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
