/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.myconf.*;
import org.myconf.dao.*;
import org.myconf.beans.*;
import org.myconf.util.*;
import java.util.*;

public class _statistics__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.myconf.AuthTag _jsp_tag0 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag1 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag2 = null;
    try {
      
//*********************************
//security
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.myconf.AuthTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setModule("admin");
      }

      _jsp_tag0.doStartTag();
      _jsp_tag0.setBodyContent(null);
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//define
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//variable
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//statistics type
int type=RequestUtils.getParam(request, "type", PaperBean.STATISTICS_BY_SUBJECT);

//paper statistics data
Map stats=PaperDAO.statistics(type);

//section iterator
Iterator secs=null;
if(type==PaperBean.STATISTICS_BY_COUNTRY || type==PaperBean.STATISTICS_BY_STATE){
	secs=stats.keySet().iterator();
}else{
	List subjects=SubjectDAO.listSubject();
	if(subjects==null){
		throw new Exception(Globals.getMessage("common", "error.unknow"));
	}
	secs=subjects.iterator();
}
if(secs==null || !secs.hasNext()){
	throw new Exception(Globals.getMessage("common", "error.unknow"));
}

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
//*********************************
//head
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/head.jsp");
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
//*********************************
//top
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/top.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_admin.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/admin/sub/mainmenu1.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      pageContext.include("/admin/sub/leftmenu1.jsp");
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      pageContext.include("/inc/stat.jsp");
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.left.statistics");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      if(type!=PaperBean.STATISTICS_BY_COUNTRY && type!=PaperBean.STATISTICS_BY_STATE){
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.statistics.subject");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      }else{
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag2.setPage("/admin/statistics.jsp?type=");
      }

      int _jspEval12 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar13 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar13 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      out.print((PaperBean.STATISTICS_BY_SUBJECT));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.statistics.subject");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      }
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      if(type==PaperBean.STATISTICS_BY_COUNTRY){
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.statistics.country");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      }else{
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag2.setPage("/admin/statistics.jsp?type=");
      }

      int _jspEval22 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar23 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar23 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      out.print((PaperBean.STATISTICS_BY_COUNTRY));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.statistics.country");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      }
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      if(type==PaperBean.STATISTICS_BY_STATE){
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.statistics.state");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      }else{
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag2.setPage("/admin/statistics.jsp?type=");
      }

      int _jspEval32 = _jsp_tag2.doStartTag();
      int _jsp_endTagVar33 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar33 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      out.print((PaperBean.STATISTICS_BY_STATE));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("menu.statistics.state");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      }
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      if(type==PaperBean.STATISTICS_BY_COUNTRY){
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("common.text.statistics.country");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      }else if(type==PaperBean.STATISTICS_BY_STATE){
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("common.text.statistics.state");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      }else{
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("common.text.statistics.subject");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      }
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("common.text.statistics.accept");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      _jsp_tag1.setKey("common.text.statistics.sum");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      
              	Map vmap=null;
              	String key=null;
              	String skey=null;
              	Iterator skeys=null;
              	int sum=0;
              	int cnt=0;
              	while(secs.hasNext()){
              	  key=(String)secs.next();
              	  if(!PaperBean.STATISTICS_SUM.equals(key)){
              	  	vmap=(Map)stats.get(key);
              	  	if(vmap==null){
              	  	  sum=0;
              	  	  skeys=null;
              	  	}else{
              	  	  sum=((Integer)vmap.remove(PaperBean.STATISTICS_SUM)).intValue();
              	  	  skeys=vmap.keySet().iterator();
              	  	}
              
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((key));
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      if(skeys!=null){
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      
                	  	while(skeys.hasNext()){
                	  	  skey=(String)skeys.next();
                	  	  cnt=((Number)vmap.get(skey)).intValue();
                	
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((skey));
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((cnt));
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((100*cnt/sum));
      pageContext.write(_jsp_string27, 0, _jsp_string27.length);
      }
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      }
      pageContext.write(_jsp_string29, 0, _jsp_string29.length);
      out.print((sum));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      }}
      pageContext.write(_jsp_string30, 0, _jsp_string30.length);
      sum=((Integer)stats.get(PaperBean.STATISTICS_SUM)).intValue();
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("common.text.statistics.all");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((sum));
      pageContext.write(_jsp_string33, 0, _jsp_string33.length);
      
//*********************************
//end content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//**********************************
//footer
//**********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string34, 0, _jsp_string34.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_statistics__jsp.java", "/myconf/admin/statistics.jsp");
    _caucho_line_map.add(19, 1);
    _caucho_line_map.add(1, 35);
    _caucho_line_map.add(6, 41);
    _caucho_line_map.add(7, 51);
    _caucho_line_map.add(8, 55);
    _caucho_line_map.add(13, 61);
    _caucho_line_map.add(27, 76);
    _caucho_line_map.add(51, 99);
    _caucho_line_map.add(56, 105);
    _caucho_line_map.add(59, 107);
    _caucho_line_map.add(64, 113);
    _caucho_line_map.add(65, 115);
    _caucho_line_map.add(66, 117);
    _caucho_line_map.add(71, 123);
    _caucho_line_map.add(77, 125);
    _caucho_line_map.add(78, 127);
    _caucho_line_map.add(85, 129);
    _caucho_line_map.add(89, 139);
    _caucho_line_map.add(90, 141);
    _caucho_line_map.add(91, 151);
    _caucho_line_map.add(92, 153);
    _caucho_line_map.add(92, 164);
    _caucho_line_map.add(92, 166);
    _caucho_line_map.add(93, 176);
    _caucho_line_map.add(94, 178);
    _caucho_line_map.add(95, 180);
    _caucho_line_map.add(96, 190);
    _caucho_line_map.add(97, 192);
    _caucho_line_map.add(97, 203);
    _caucho_line_map.add(97, 205);
    _caucho_line_map.add(98, 215);
    _caucho_line_map.add(99, 217);
    _caucho_line_map.add(100, 219);
    _caucho_line_map.add(101, 229);
    _caucho_line_map.add(102, 231);
    _caucho_line_map.add(102, 242);
    _caucho_line_map.add(102, 244);
    _caucho_line_map.add(103, 254);
    _caucho_line_map.add(116, 256);
    _caucho_line_map.add(117, 258);
    _caucho_line_map.add(118, 268);
    _caucho_line_map.add(119, 270);
    _caucho_line_map.add(120, 280);
    _caucho_line_map.add(121, 282);
    _caucho_line_map.add(122, 292);
    _caucho_line_map.add(125, 304);
    _caucho_line_map.add(127, 307);
    _caucho_line_map.add(158, 339);
    _caucho_line_map.add(159, 341);
    _caucho_line_map.add(168, 351);
    _caucho_line_map.add(172, 363);
    _caucho_line_map.add(182, 365);
    _caucho_line_map.add(187, 371);
    _caucho_line_map.add(192, 377);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/statistics.jsp"), 1178210604000L, 7436L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string9;
  private static byte []_jsp_string19;
  private static byte []_jsp_string10;
  private static byte []_jsp_string6;
  private static byte []_jsp_string16;
  private static byte []_jsp_string8;
  private static byte []_jsp_string1;
  private static byte []_jsp_string27;
  private static byte []_jsp_string34;
  private static byte []_jsp_string26;
  private static byte []_jsp_string0;
  private static byte []_jsp_string14;
  private static byte []_jsp_string17;
  private static byte []_jsp_string21;
  private static byte []_jsp_string28;
  private static byte []_jsp_string15;
  private static byte []_jsp_string24;
  private static byte []_jsp_string4;
  private static byte []_jsp_string5;
  private static byte []_jsp_string20;
  private static byte []_jsp_string33;
  private static byte []_jsp_string2;
  private static byte []_jsp_string29;
  private static byte []_jsp_string31;
  private static byte []_jsp_string7;
  private static byte []_jsp_string12;
  private static byte []_jsp_string32;
  private static byte []_jsp_string3;
  private static byte []_jsp_string11;
  private static byte []_jsp_string30;
  private static byte []_jsp_string18;
  private static byte []_jsp_string22;
  private static byte []_jsp_string13;
  private static byte []_jsp_string23;
  private static byte []_jsp_string25;
  static {
    try {
      _jsp_string9 = "\r\n          	<a href=\"".getBytes("UTF8");
      _jsp_string19 = "</td>\r\n                <td width=\"29%\" class=\"table_head\" nowrap>".getBytes("UTF8");
      _jsp_string10 = "\" class=\"pagemenu\">".getBytes("UTF8");
      _jsp_string6 = "</b></td>\r\n        </tr>\r\n        <tr> \r\n          <td align=\"right\" class=\"pagecontent_right\">\r\n          	".getBytes("UTF8");
      _jsp_string16 = "\r\n                	".getBytes("UTF8");
      _jsp_string8 = "</span> \r\n          	".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n".getBytes("UTF8");
      _jsp_string27 = "%</td>\r\n                    </tr>\r\n                    ".getBytes("UTF8");
      _jsp_string34 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string26 = "</td>\r\n                      <td width=\"28%\">".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string14 = "\r\n          	> <a href=\"".getBytes("UTF8");
      _jsp_string17 = "\r\n                ".getBytes("UTF8");
      _jsp_string21 = "\r\n              <tr> \r\n                <td valign=\"top\" class=\"table_cell\">".getBytes("UTF8");
      _jsp_string28 = "\r\n                  </table>\r\n                  ".getBytes("UTF8");
      _jsp_string15 = "\r\n        </tr>\r\n      </table>\r\n      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr> \r\n          <td> <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n              <tr> \r\n                <td width=\"52%\"> <div class=\"spacer_20\"></div></td>\r\n              </tr>\r\n            </table>\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"3\" cellspacing=\"1\" class=\"table\">\r\n              <tr> \r\n                <td width=\"30%\" class=\"table_head\" nowrap>\r\n                ".getBytes("UTF8");
      _jsp_string24 = "\r\n                    <tr> \r\n                      <td width=\"47%\">".getBytes("UTF8");
      _jsp_string4 = "\r\n			".getBytes("UTF8");
      _jsp_string5 = "\r\n          </td>\r\n        </tr>\r\n      </table></td>\r\n    <td width=\"598\" valign=\"top\" class=\"pagecontent\">\r\n	  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <tr> \r\n          <td class=\"pagecontent_title\"><b>".getBytes("UTF8");
      _jsp_string20 = "</td>\r\n              </tr>\r\n              ".getBytes("UTF8");
      _jsp_string33 = "</td>\r\n              </tr>\r\n            </table>\r\n            \r\n          </td>\r\n        </tr>\r\n      </table>\r\n    </td>\r\n  </tr>\r\n</table>\r\n".getBytes("UTF8");
      _jsp_string2 = "\r\n\r\n<body>\r\n".getBytes("UTF8");
      _jsp_string29 = "\r\n                </td>\r\n                <td valign=\"top\" class=\"table_cell\">".getBytes("UTF8");
      _jsp_string31 = "\r\n              <tr> \r\n                <td valign=\"top\" class=\"table_cell\" style=\"color:blue\">".getBytes("UTF8");
      _jsp_string7 = "\r\n          	<span class=\"pagemenu_visited\">".getBytes("UTF8");
      _jsp_string12 = "\r\n          	".getBytes("UTF8");
      _jsp_string32 = "</td>\r\n                <td class=\"table_cell\">&nbsp;</td>\r\n                <td valign=\"top\" class=\"table_cell\" style=\"color:blue\">".getBytes("UTF8");
      _jsp_string3 = "\r\n<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"MARGIN-TOP: 10px;\">\r\n  <tr>\r\n    <td width=\"180\" height=\"55\" valign=\"top\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"leftmenu\">\r\n        <tr> \r\n          <td height=\"41\">\r\n			".getBytes("UTF8");
      _jsp_string11 = "</a> \r\n          	".getBytes("UTF8");
      _jsp_string30 = "\r\n              ".getBytes("UTF8");
      _jsp_string18 = "\r\n                </td>\r\n                <td width=\"41%\" nowrap class=\"table_head\">".getBytes("UTF8");
      _jsp_string22 = "</td>\r\n                <td nowrap class=\"table_cell\">\r\n                  ".getBytes("UTF8");
      _jsp_string13 = "\r\n          	> <span class=\"pagemenu_visited\">".getBytes("UTF8");
      _jsp_string23 = "\r\n                  <table width=\"98%\" border=\"0\" cellspacing=\"2\" cellpadding=\"0\">\r\n                	".getBytes("UTF8");
      _jsp_string25 = "</td>\r\n                      <td width=\"25%\">".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
