/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _admin._sub;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _leftmenu1__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.apache.struts.taglib.bean.MessageTag _jsp_tag0 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag1 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setBundle("admin");
      }

      _jsp_tag0.setKey("menu.top.submission_review");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag1.setPage("/admin/subins.jsp");
      int _jspEval5 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar6 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar6 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.submission.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.submission");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      _jsp_tag1.setPage("/admin/reviewins.jsp");
      int _jspEval15 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar16 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar16 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.review.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.review");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      _jsp_tag1.setPage("/admin/paper.jsp");
      int _jspEval25 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar26 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar26 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.paper.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.paper");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag1.setPage("/admin/result.jsp");
      int _jspEval35 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar36 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar36 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.result.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.result");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_tag1.setPage("/admin/export.jsp");
      int _jspEval45 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar46 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar46 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.export.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.export");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_tag1.setPage("/admin/download.jsp");
      int _jspEval55 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar56 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar56 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.download.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.download");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      _jsp_tag1.setPage("/admin/statistics.jsp");
      int _jspEval65 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar66 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar66 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.statistics.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("menu.left.statistics");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      _jsp_tag1.setPage("/admin/publish.jsp");
      int _jspEval75 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar76 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar76 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag0.setKey("menu.left.publish.ins");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      _jsp_tag0.setKey("menu.left.publish");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_leftmenu1__jsp.java", "/myconf/admin/sub/leftmenu1.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 29);
    _caucho_line_map.add(6, 32);
    _caucho_line_map.add(9, 42);
    _caucho_line_map.add(9, 54);
    _caucho_line_map.add(9, 57);
    _caucho_line_map.add(10, 60);
    _caucho_line_map.add(10, 66);
    _caucho_line_map.add(10, 69);
    _caucho_line_map.add(11, 72);
    _caucho_line_map.add(11, 78);
    _caucho_line_map.add(11, 81);
    _caucho_line_map.add(12, 84);
    _caucho_line_map.add(12, 90);
    _caucho_line_map.add(12, 93);
    _caucho_line_map.add(13, 96);
    _caucho_line_map.add(13, 102);
    _caucho_line_map.add(13, 105);
    _caucho_line_map.add(14, 108);
    _caucho_line_map.add(14, 114);
    _caucho_line_map.add(14, 117);
    _caucho_line_map.add(15, 120);
    _caucho_line_map.add(15, 126);
    _caucho_line_map.add(15, 129);
    _caucho_line_map.add(16, 132);
    _caucho_line_map.add(16, 138);
    _caucho_line_map.add(16, 141);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/sub/leftmenu1.jsp"), 1183083361265L, 2210L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string9;
  private static byte []_jsp_string12;
  private static byte []_jsp_string1;
  private static byte []_jsp_string5;
  private static byte []_jsp_string11;
  private static byte []_jsp_string7;
  private static byte []_jsp_string8;
  private static byte []_jsp_string10;
  private static byte []_jsp_string13;
  private static byte []_jsp_string6;
  private static byte []_jsp_string4;
  private static byte []_jsp_string0;
  private static byte []_jsp_string2;
  private static byte []_jsp_string3;
  static {
    try {
      _jsp_string9 = "</a></span> \r\n      <span class=\"paper_download\"><a href=\"".getBytes("UTF8");
      _jsp_string12 = "\"><b>".getBytes("UTF8");
      _jsp_string1 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"embed_module\">\r\n  <tr>\r\n    <td class=\"module_title\"><b>".getBytes("UTF8");
      _jsp_string5 = "</a></span> \r\n      <span class=\"paper_setting\"><a href=\"".getBytes("UTF8");
      _jsp_string11 = "</a></span> \r\n      <span class=\"paper_publish\"><a href=\"".getBytes("UTF8");
      _jsp_string7 = "</a></span> \r\n      <span class=\"paper_review\"><a href=\"".getBytes("UTF8");
      _jsp_string8 = "</a></span> \r\n      <span class=\"paper_export\"><a href=\"".getBytes("UTF8");
      _jsp_string10 = "</a></span> \r\n      <span class=\"paper_stat\"><a href=\"".getBytes("UTF8");
      _jsp_string13 = "</b></a></span></td>\r\n  </tr>\r\n</table>".getBytes("UTF8");
      _jsp_string6 = "</a></span> \r\n      <span class=\"paper_diliver\"><a href=\"".getBytes("UTF8");
      _jsp_string4 = "\">".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string2 = "</b></td>\r\n  </tr>\r\n  <tr>\r\n    <td class=\"module_content\"> <span class=\"paper_setting\"><a href=\"".getBytes("UTF8");
      _jsp_string3 = "\" title=\"".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
