/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _expert;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.myconf.beans.*;
import org.myconf.dao.*;
import org.myconf.util.*;
import java.util.*;

public class _reviewed__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.myconf.AuthTag _jsp_tag0 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag1 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag2 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag3 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag4 = null;
    try {
      
//*********************************
//security
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.myconf.AuthTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setModule("expert");
      }

      _jsp_tag0.doStartTag();
      _jsp_tag0.setBodyContent(null);
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//define
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      org.myconf.SessionUserObject uinfo;
      uinfo = (org.myconf.SessionUserObject) request.getAttribute("uinfo");
      if (uinfo == null) {
        uinfo = new org.myconf.SessionUserObject();
        request.setAttribute("uinfo", uinfo);
      }
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//variable
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//expert reviewing
List reviews=ReviewDAO.listExpertReviews(uinfo.getId(), ReviewBean.REVIEW_STATUS_FINISH);
ReviewBean review=null;
PaperBean paper=null;

//review date
ConfigBean conf=ConfigDAO.getCurrentConfig(ConfigBean.CONFIG_ID);
Date begin=null;
Date end=null;
if(conf!=null){
	if(conf.getReviewBeginDate()>0){
		begin=new Date(conf.getReviewBeginDate());
	}
	if(conf.getReviewEndDate()>0){
		end=new Date(conf.getReviewEndDate());
	}
}
String beginStr=StringUtils.exportDate(begin, "yyyy-MM-dd HH:mm", "-- -- --");
String endStr=StringUtils.exportDate(end, "yyyy-MM-dd HH:mm", "-- -- --");

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
//*********************************
//head
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/head.jsp");
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
//*********************************
//top
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/top.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_expert.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/expert/sub/mainmenu4.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag1.setPage("/expert/reviewpaper.jsp?id=");
      int _jspEval6 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar7 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar7 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag1.setPage("/images/rounded_top.gif");
      int _jspEval10 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar11 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar11 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      if(conf!=null && conf.getReviewBeginDate()<System.currentTimeMillis() && conf.getReviewEndDate()>System.currentTimeMillis()){
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag2.setKey("menu.top.reviewed");
      _jsp_tag2.setBundle("expert");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag2.setKey("page.reviewed.ins1");
      _jsp_tag2.setBundle("expert");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      if (_jsp_tag3 == null) {
        _jsp_tag3 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag3.setPageContext(pageContext);
        _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag3.setBundle("expert");
        _jsp_tag3.setKey("page.reviewing.ins3");
      }

      _jsp_tag3.setArg0(beginStr);
      _jsp_tag3.setArg1(endStr);
      _jsp_tag3.doStartTag();
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      if(reviews!=null && reviews.size()>0){
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag2.setKey("common.text.no");
      _jsp_tag2.setBundle("admin");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      _jsp_tag2.setKey("common.text.title");
      _jsp_tag2.setBundle("admin");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      _jsp_tag2.setKey("common.text.subject");
      _jsp_tag2.setBundle("admin");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      if (_jsp_tag4 == null) {
        _jsp_tag4 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag4.setPageContext(pageContext);
        _jsp_tag4.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag4.setKey("common.text.modify");
      _jsp_tag4.doStartTag();
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      
          	for(int i=0;i<reviews.size();i++){
          	  review=(ReviewBean)reviews.get(i);
          	  paper=review.getPaper();
          
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((paper.getId()));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((paper.getTitle()));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((paper.getSubject().getSubject()));
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      if (_jsp_tag4 == null) {
        _jsp_tag4 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag4.setPageContext(pageContext);
        _jsp_tag4.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag4.setKey("common.text.modify");
      _jsp_tag4.doStartTag();
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((review.getId()));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag1.setPage("/images/review.gif");
      int _jspEval38 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar39 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar39 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      }
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      }else{
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      if (_jsp_tag4 == null) {
        _jsp_tag4 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag4.setPageContext(pageContext);
        _jsp_tag4.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag4.setKey("common.text.norecord");
      _jsp_tag4.doStartTag();
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      }
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      }else{
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      if (_jsp_tag4 == null) {
        _jsp_tag4 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag4.setPageContext(pageContext);
        _jsp_tag4.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag4.setKey("common.ins.not.begin.review");
      _jsp_tag4.doStartTag();
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      }
      pageContext.write(_jsp_string27, 0, _jsp_string27.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag1.setPage("/images/rounded_bottom.gif");
      int _jspEval48 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar49 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar49 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      
//*********************************
//end content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//**********************************
//footer
//**********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string29, 0, _jsp_string29.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      if (_jsp_tag3 != null)
        _jsp_tag3.release();
      if (_jsp_tag4 != null)
        _jsp_tag4.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_reviewed__jsp.java", "/myconf/expert/reviewed.jsp");
    _caucho_line_map.add(18, 1);
    _caucho_line_map.add(1, 36);
    _caucho_line_map.add(6, 42);
    _caucho_line_map.add(7, 52);
    _caucho_line_map.add(8, 56);
    _caucho_line_map.add(13, 62);
    _caucho_line_map.add(22, 77);
    _caucho_line_map.add(27, 83);
    _caucho_line_map.add(50, 105);
    _caucho_line_map.add(55, 111);
    _caucho_line_map.add(58, 113);
    _caucho_line_map.add(63, 119);
    _caucho_line_map.add(64, 121);
    _caucho_line_map.add(65, 123);
    _caucho_line_map.add(70, 129);
    _caucho_line_map.add(74, 131);
    _caucho_line_map.add(80, 143);
    _caucho_line_map.add(85, 149);
    _caucho_line_map.add(88, 151);
    _caucho_line_map.add(96, 161);
    _caucho_line_map.add(97, 165);
    _caucho_line_map.add(112, 179);
    _caucho_line_map.add(113, 189);
    _caucho_line_map.add(114, 193);
    _caucho_line_map.add(115, 197);
    _caucho_line_map.add(117, 206);
    _caucho_line_map.add(124, 214);
    _caucho_line_map.add(125, 216);
    _caucho_line_map.add(126, 218);
    _caucho_line_map.add(126, 227);
    _caucho_line_map.add(126, 229);
    _caucho_line_map.add(129, 241);
    _caucho_line_map.add(134, 245);
    _caucho_line_map.add(137, 254);
    _caucho_line_map.add(143, 258);
    _caucho_line_map.add(147, 267);
    _caucho_line_map.add(152, 269);
    _caucho_line_map.add(156, 281);
    _caucho_line_map.add(161, 287);
    _caucho_line_map.add(166, 293);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("expert/reviewed.jsp"), 1182653989453L, 6216L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string16;
  private static byte []_jsp_string3;
  private static byte []_jsp_string9;
  private static byte []_jsp_string28;
  private static byte []_jsp_string5;
  private static byte []_jsp_string1;
  private static byte []_jsp_string6;
  private static byte []_jsp_string8;
  private static byte []_jsp_string10;
  private static byte []_jsp_string25;
  private static byte []_jsp_string18;
  private static byte []_jsp_string26;
  private static byte []_jsp_string19;
  private static byte []_jsp_string20;
  private static byte []_jsp_string13;
  private static byte []_jsp_string29;
  private static byte []_jsp_string7;
  private static byte []_jsp_string0;
  private static byte []_jsp_string4;
  private static byte []_jsp_string21;
  private static byte []_jsp_string22;
  private static byte []_jsp_string24;
  private static byte []_jsp_string11;
  private static byte []_jsp_string14;
  private static byte []_jsp_string23;
  private static byte []_jsp_string12;
  private static byte []_jsp_string2;
  private static byte []_jsp_string27;
  private static byte []_jsp_string17;
  private static byte []_jsp_string15;
  static {
    try {
      _jsp_string16 = "</td>\r\n            <td class=\"table_cell\">".getBytes("UTF8");
      _jsp_string3 = "\r\n<br>\r\n<script language=\"JavaScript\">\r\nfunction reviewPaper(rid) {\r\n	window.open(\"".getBytes("UTF8");
      _jsp_string9 = "</li></td>\r\n                </tr>\r\n              </table></td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"88%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td width=\"52%\"> <div class=\"spacer_20\"></div>\r\n              <div class=\"line_dashed\"></div>\r\n              <div class=\"spacer_10\"></div></td>\r\n          </tr>\r\n        </table>\r\n        ".getBytes("UTF8");
      _jsp_string28 = "\" width=\"778\" height=\"5\"></TD>\r\n    </TR>\r\n  </TBODY>\r\n</TABLE>\r\n".getBytes("UTF8");
      _jsp_string5 = "\" width=\"778\" height=\"5\"></TD>\r\n    </TR>\r\n    <TR> \r\n      <TD width=1 height=\"73\" noWrap bgColor=#a9a9a9></TD>\r\n      <TD width=776 noWrap>\r\n      	".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n".getBytes("UTF8");
      _jsp_string6 = "\r\n		<table width=\"99%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n          <tr> \r\n            <td class=\"pagecontent_title\"><b>".getBytes("UTF8");
      _jsp_string8 = "</li>\r\n                    <li>".getBytes("UTF8");
      _jsp_string10 = "\r\n        <table width=\"88%\" border=\"0\" align=\"center\" cellpadding=\"3\" cellspacing=\"1\" class=\"table\">\r\n          <tr> \r\n            <td width=\"6%\" align=\"center\" nowrap class=\"table_head\">".getBytes("UTF8");
      _jsp_string25 = "\r\n	  	<TABLE width=518 border=0 align=\"center\" cellPadding=5 cellSpacing=0>\r\n          <TBODY>\r\n            <TR> \r\n              <TD align=\"center\" style=\"font-size:16px;\" class=\"redins\">".getBytes("UTF8");
      _jsp_string18 = "\" href=\"javascript:reviewPaper(".getBytes("UTF8");
      _jsp_string26 = "</TD>\r\n            </TR>\r\n          </TBODY>\r\n        </TABLE> \r\n        ".getBytes("UTF8");
      _jsp_string19 = ")\"><img src=\"".getBytes("UTF8");
      _jsp_string20 = "\" width=\"20\" height=\"22\" border=\"0\"></a> \r\n            </td>\r\n          </tr>\r\n          ".getBytes("UTF8");
      _jsp_string13 = "</td>\r\n            <td width=\"6%\" align=\"center\" class=\"table_head\" nowrap>".getBytes("UTF8");
      _jsp_string29 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string7 = "</b></td>\r\n          </tr>\r\n        </table>\r\n        <br>\r\n        <table width=\"88%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form\">\r\n          <tr> \r\n            <td><table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_note\">\r\n                <tr> \r\n                  <td> <li>".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string4 = "\"+rid, \"review\", \"resizable=no,scrollbars=yes,height=600,width=800\");\r\n}\r\n</script>\r\n<TABLE width=778 height=\"84\" border=0 align=\"center\" cellPadding=0 cellSpacing=0 summary=null>\r\n  <TBODY>\r\n    <TR> \r\n      <TD noWrap width=778 colSpan=2 height=5><img src=\"".getBytes("UTF8");
      _jsp_string21 = "\r\n        </table>\r\n        ".getBytes("UTF8");
      _jsp_string22 = "\r\n        <table width=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"0\">\r\n          <tr> \r\n            <td align=\"center\" class=\"blackbold\" nowrap>".getBytes("UTF8");
      _jsp_string24 = "\r\n        <br>\r\n        ".getBytes("UTF8");
      _jsp_string11 = "</td>\r\n            <td width=\"52%\" class=\"table_head\" nowrap>".getBytes("UTF8");
      _jsp_string14 = "</td>\r\n          </tr>\r\n          ".getBytes("UTF8");
      _jsp_string23 = "</td>\r\n          </tr>\r\n        </table>\r\n        ".getBytes("UTF8");
      _jsp_string12 = "</td>\r\n            <td width=\"36%\" nowrap class=\"table_head\">".getBytes("UTF8");
      _jsp_string2 = "\r\n\r\n<body>\r\n".getBytes("UTF8");
      _jsp_string27 = "\r\n      </TD>\r\n      <TD noWrap width=1 bgColor=#a9a9a9></TD>\r\n    </TR>\r\n    <TR> \r\n      <TD noWrap width=778 colSpan=2 height=6><img src=\"".getBytes("UTF8");
      _jsp_string17 = "</td>\r\n            <td align=\"center\" class=\"table_cell\"><a title=\"".getBytes("UTF8");
      _jsp_string15 = "\r\n          <tr> \r\n            <td align=\"center\" class=\"table_cell\">".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
