/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _submission;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _index__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.apache.struts.taglib.bean.MessageTag _jsp_tag0 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag1 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag2 = null;
    try {
      
//*********************************
//define
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
//*********************************
//head
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/head.jsp");
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.include("/inc/top_sim.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_author.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag0.setKey("page.login.please_input");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag0.setKey("common.button.login");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      _jsp_tag0.setKey("common.button.register");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      _jsp_tag0.setKey("error.email.not.null");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag0.setKey("error.email.wrong.format");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_tag0.setKey("error.password.not.null");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_tag0.setKey("error.confirmpass.not.null");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      _jsp_tag0.setKey("error.password.not.less.six");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      _jsp_tag0.setKey("error.confirmpass.not.match");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag1.setPage("/user.do");
      int _jspEval29 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar30 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar30 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag2.setBundle("author");
      }

      _jsp_tag2.setKey("page.login.olduser");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      _jsp_tag2.setKey("page.login.newuser");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      _jsp_tag0.setKey("common.textbox.email");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      _jsp_tag0.setKey("common.textbox.password");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      _jsp_tag0.setKey("common.textbox.confirmpass");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      _jsp_tag0.setKey("page.register.password");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      _jsp_tag0.setKey("page.login.remember");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      _jsp_tag1.setPage("/forgetpass.jsp");
      int _jspEval54 = _jsp_tag1.doStartTag();
      int _jsp_endTagVar55 = _jsp_tag1.doEndTag();
      if (_jsp_endTagVar55 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      _jsp_tag0.setKey("page.login.forget");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      _jsp_tag0.setKey("common.button.login");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      _jsp_tag0.setKey("common.button.back");
      _jsp_tag0.doStartTag();
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_index__jsp.java", "/myconf/submission/index.jsp");
    _caucho_line_map.add(7, 1);
    _caucho_line_map.add(1, 30);
    _caucho_line_map.add(6, 36);
    _caucho_line_map.add(12, 40);
    _caucho_line_map.add(17, 46);
    _caucho_line_map.add(20, 48);
    _caucho_line_map.add(21, 50);
    _caucho_line_map.add(25, 52);
    _caucho_line_map.add(38, 61);
    _caucho_line_map.add(46, 64);
    _caucho_line_map.add(81, 67);
    _caucho_line_map.add(86, 70);
    _caucho_line_map.add(92, 73);
    _caucho_line_map.add(98, 76);
    _caucho_line_map.add(103, 79);
    _caucho_line_map.add(109, 82);
    _caucho_line_map.add(120, 85);
    _caucho_line_map.add(129, 97);
    _caucho_line_map.add(131, 107);
    _caucho_line_map.add(139, 110);
    _caucho_line_map.add(145, 113);
    _caucho_line_map.add(151, 116);
    _caucho_line_map.add(153, 119);
    _caucho_line_map.add(159, 122);
    _caucho_line_map.add(159, 125);
    _caucho_line_map.add(159, 131);
    _caucho_line_map.add(165, 134);
    _caucho_line_map.add(166, 137);
    _caucho_line_map.add(173, 140);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("submission/index.jsp"), 1180693282000L, 6833L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string6;
  private static byte []_jsp_string13;
  private static byte []_jsp_string22;
  private static byte []_jsp_string23;
  private static byte []_jsp_string12;
  private static byte []_jsp_string10;
  private static byte []_jsp_string5;
  private static byte []_jsp_string1;
  private static byte []_jsp_string11;
  private static byte []_jsp_string9;
  private static byte []_jsp_string25;
  private static byte []_jsp_string24;
  private static byte []_jsp_string20;
  private static byte []_jsp_string18;
  private static byte []_jsp_string0;
  private static byte []_jsp_string4;
  private static byte []_jsp_string17;
  private static byte []_jsp_string19;
  private static byte []_jsp_string14;
  private static byte []_jsp_string7;
  private static byte []_jsp_string2;
  private static byte []_jsp_string3;
  private static byte []_jsp_string21;
  private static byte []_jsp_string8;
  private static byte []_jsp_string16;
  private static byte []_jsp_string15;
  static {
    try {
      _jsp_string6 = "';\r\n		submission.sb.name='eventSubmit_Register';\r\n	}\r\n}\r\n</script>\r\n<SCRIPT language=\"javascript\">\r\nfunction init()\r\n{\r\n	var rem=getCookie(\"rem\");\r\n	var uname=getCookie(\"uname\")\r\n	if(!rem||rem==1){\r\n		submission.rem.checked=true;\r\n	}\r\n	if(uname&&uname!=0){\r\n		submission.email.value=uname;\r\n		submission.password.focus();\r\n	}else{\r\n		submission.email.focus();\r\n	}\r\n}\r\n\r\nfunction save()\r\n{\r\n	if(submission.rem.checked){\r\n		setCookie(\"rem\", 1);\r\n		setCookie(\"uname\", submission.email.value);\r\n	}else{\r\n		setCookie(\"rem\", 0);\r\n		setCookie(\"uname\", 0);\r\n	}\r\n}\r\n\r\nfunction checkForm()\r\n{\r\n	if (submission.email.value.length == 0) {\r\n		alert(\"".getBytes("UTF8");
      _jsp_string13 = "\" method=\"post\" onSubmit=\"save();return checkForm();\" name=\"submission\" id=\"submission\">\r\n        <input name=\"fromPage\" type=\"hidden\" id=\"fromPage\" value=\"/submission/mypaper.jsp\">\r\n        <br>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form\">\r\n          <tr>\r\n            <td><table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_note\">\r\n                <tr> \r\n                  <td>\r\n                    <input name=\"st\" type=\"radio\" value=\"1\" onClick=\"switchForm();\" checked>\r\n                    <span id=\"s1\">".getBytes("UTF8");
      _jsp_string22 = "</a> \r\n            </td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td class=\"form_row_submit\"><input type=\"submit\" id=\"sb\" name=\"eventSubmit_Create\" value=\"".getBytes("UTF8");
      _jsp_string23 = "\" class=\"button\"> \r\n              <input name=\"Button\" type=\"button\" onClick=\"window.history.back()\" class=\"button\" value=\"".getBytes("UTF8");
      _jsp_string12 = "\");\r\n			submission.password2.select();\r\n			submission.password2.focus();\r\n			return false;\r\n		}\r\n	}\r\n	return true;\r\n}\r\n</script>\r\n<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"MARGIN-TOP: 10px;\">\r\n  <tr> \r\n    <td valign=\"top\" class=\"pagecontent\"><form action=\"".getBytes("UTF8");
      _jsp_string10 = "\");\r\n			submission.password2.focus();\r\n			return false;\r\n		}\r\n		if( submission.password.value.length<6) {\r\n			alert(\"".getBytes("UTF8");
      _jsp_string5 = "';\r\n		submission.sb.name='eventSubmit_Login';\r\n	}\r\n	if(submission.st[1].checked){\r\n		changeStyle('s1','');\r\n		changeStyle('s2','blackbold');\r\n		hideLayer('remember');\r\n		showLayer('confirm');\r\n		submission.sb.value='".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n".getBytes("UTF8");
      _jsp_string11 = "\");\r\n			submission.password.select();\r\n			submission.password.focus();\r\n			return false;\r\n		}\r\n		if (submission.password.value != submission.password2.value) {\r\n			alert(\"".getBytes("UTF8");
      _jsp_string9 = "\");\r\n		submission.password.focus();\r\n		return false;\r\n	}\r\n	if(submission.st[1].checked){\r\n		if (submission.password2.value.length == 0) {\r\n			alert(\"".getBytes("UTF8");
      _jsp_string25 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string24 = "\">\r\n          </tr>\r\n        </table>\r\n        <br>\r\n      </form></td>\r\n  </tr>\r\n</table>\r\n".getBytes("UTF8");
      _jsp_string20 = " &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"".getBytes("UTF8");
      _jsp_string18 = "</td>\r\n            <td width=\"75%\" class=\"form_row_content\"><input name=\"password2\" type=\"password\" id=\"password2\" size=\"32\">\r\n              ".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string4 = "</span></td>\r\n    <td width=\"310\" style=\"PADDING-TOP: 2px;\" align=\"right\" class=\"channel_bar_bg\">&nbsp; \r\n      </td>\r\n    <td width=\"10\" class=\"channel_bar_right\">&nbsp;</td>\r\n  </tr>\r\n</table>\r\n<script language=\"JavaScript\">\r\nfunction switchForm(){\r\n	if(submission.st[0].checked){\r\n		changeStyle('s1','blackbold');\r\n		changeStyle('s2','');\r\n		hideLayer('confirm');\r\n		showLayer('remember');\r\n		submission.sb.value='".getBytes("UTF8");
      _jsp_string17 = "</td>\r\n            <td width=\"75%\" class=\"form_row_content\"><input name=\"password\" type=\"password\" id=\"password\" size=\"32\"></td>\r\n          </tr>\r\n        </table>\r\n        <table id=\"confirm\" width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td width=\"25%\" class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string19 = "</td>\r\n          </tr>\r\n        </table>\r\n        <table id=\"remember\" width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td class=\"form_row_content\"> <input name=\"rem\" type=\"checkbox\" id=\"rem\" value=\"1\" checked>\r\n              ".getBytes("UTF8");
      _jsp_string14 = "</span><br>\r\n                    <input type=\"radio\" name=\"st\" value=\"2\" onClick=\"switchForm();\">\r\n                    <span id=\"s2\">".getBytes("UTF8");
      _jsp_string7 = "\");\r\n		submission.email.focus();\r\n		return false;\r\n	}\r\n	if (!isEmail(submission.email.value)) {\r\n		alert(\"".getBytes("UTF8");
      _jsp_string2 = "\r\n\r\n<body onLoad=\"switchForm();init();\">\r\n".getBytes("UTF8");
      _jsp_string3 = "\r\n<table width=\"778\" height=\"31\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n  <tr> \r\n    <td width=\"10\" class=\"channel_bar_left\">&nbsp;</td>\r\n    <td width=\"448\" class=\"channel_bar_bg\"><span class=\"bartitle\">&nbsp;".getBytes("UTF8");
      _jsp_string21 = "\" target=\"_blank\" class=\"blue\">".getBytes("UTF8");
      _jsp_string8 = "\");\r\n		submission.email.focus();\r\n		submission.email.select();\r\n		return false;\r\n	}\r\n	if (submission.password.value.length == 0) {\r\n		alert(\"".getBytes("UTF8");
      _jsp_string16 = "</td>\r\n            <td width=\"75%\" class=\"form_row_content\"><input name=\"email\" type=\"text\" id=\"email\" size=\"32\"></td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td width=\"25%\" class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string15 = "</span> \r\n                  </td>\r\n                </tr>\r\n              </table></td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td width=\"25%\" class=\"form_row_title\">".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
