/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.myconf.*;

public class _login__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.myconf.AuthTag _jsp_tag0 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag1 = null;
    try {
      
//*********************************
//\u00d2\u00b3\u00c3\u00e6\u00b0\u00b2\u00c8\u00ab
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.myconf.AuthTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setModule("");
      }

      _jsp_tag0.doStartTag();
      _jsp_tag0.setBodyContent(null);
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//\u00c9\u00f9\u00c3\u00f7\u00ba\u00cd\u00d2\u00fd\u00d3\u00c3
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setBundle("admin");
      }

      _jsp_tag1.setKey("common.title.keyword");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.include("/inc/top_sim.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_login.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_tag1.setKey("page.login.please_input");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_tag1.setKey("common.textbox.email");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      _jsp_tag1.setKey("common.textbox.password");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      _jsp_tag1.setKey("common.button.login");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_tag1.setKey("common.button.back");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_login__jsp.java", "/admin/login.jsp");
    _caucho_line_map.add(15, 1);
    _caucho_line_map.add(1, 30);
    _caucho_line_map.add(6, 36);
    _caucho_line_map.add(7, 46);
    _caucho_line_map.add(8, 50);
    _caucho_line_map.add(13, 56);
    _caucho_line_map.add(20, 60);
    _caucho_line_map.add(27, 70);
    _caucho_line_map.add(28, 72);
    _caucho_line_map.add(32, 74);
    _caucho_line_map.add(45, 77);
    _caucho_line_map.add(51, 80);
    _caucho_line_map.add(57, 83);
    _caucho_line_map.add(58, 86);
    _caucho_line_map.add(65, 89);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/login.jsp"), 1175392109708L, 3034L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string7;
  private static byte []_jsp_string4;
  private static byte []_jsp_string3;
  private static byte []_jsp_string5;
  private static byte []_jsp_string8;
  private static byte []_jsp_string9;
  private static byte []_jsp_string6;
  private static byte []_jsp_string1;
  private static byte []_jsp_string0;
  private static byte []_jsp_string2;
  static {
    try {
      _jsp_string7 = "\"> \r\n              <input name=\"back\" type=\"button\" class=\"button\" onClick=\"window.history.back()\" id=\"back\" value=\"".getBytes("UTF8");
      _jsp_string4 = "</strong></td>\r\n    <td width=\"310\" style=\"PADDING-TOP: 2px;\" align=\"right\" class=\"channel_bar_bg\">&nbsp; \r\n      </td>\r\n    <td width=\"10\" class=\"channel_bar_right\">&nbsp;</td>\r\n  </tr>\r\n</table>\r\n<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"MARGIN-TOP: 10px;\">\r\n  <tr> \r\n    <td width=\"598\" height=\"55\" valign=\"top\" class=\"pagecontent\"><form action=\"/login.do\" method=\"post\" name=\"login\" id=\"login\">\r\n        <input name=\"url\" type=\"hidden\" id=\"url\" value=\"1\">\r\n        <br>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string3 = "\r\n<table width=\"778\" height=\"31\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n  <tr> \r\n    <td width=\"10\" class=\"channel_bar_left\">&nbsp;</td>\r\n    <td width=\"448\" class=\"channel_bar_bg\"><strong style=\"font-size:14px\">&nbsp;".getBytes("UTF8");
      _jsp_string5 = "</td>\r\n            <td class=\"form_row_content\"><input name=\"email\" type=\"text\" id=\"email\" size=\"32\"></td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string8 = "\"> </td>\r\n          </tr>\r\n        </table>\r\n        <br>\r\n      </form></td>\r\n  </tr>\r\n</table>\r\n".getBytes("UTF8");
      _jsp_string9 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string6 = "</td>\r\n            <td class=\"form_row_content\"><input name=\"password\" type=\"password\" id=\"password\" size=\"32\"></td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"60%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td class=\"form_row_submit\"><input name=\"eventSubmit_Login\" type=\"submit\" class=\"button\" id=\"eventSubmit_Login\" value=\"".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n<title>MyConf.org--".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string2 = "</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<link href=\"css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n<link href=\"css/global.css\" rel=\"stylesheet\" type=\"text/css\">\r\n</head>\r\n\r\n<body>\r\n".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
