/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _useradds__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, "/error.jsp", true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.myconf.AuthTag _jsp_tag0 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag1 = null;
    org.apache.struts.taglib.bean.MessageTag _jsp_tag2 = null;
    org.apache.struts.taglib.html.RewriteTag _jsp_tag3 = null;
    try {
      
//*********************************
//security
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.myconf.AuthTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setModule("admin");
      }

      _jsp_tag0.doStartTag();
      _jsp_tag0.setBodyContent(null);
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//define
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
//*********************************
//head
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/head.jsp");
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
//*********************************
//top
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/top.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/logo_admin.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//*********************************
//content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/admin/sub/mainmenu3.jsp");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      pageContext.include("/admin/sub/leftmenu3.jsp");
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      pageContext.include("/inc/stat.jsp");
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag1.setKey("error.expert.list.not.null");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.bean.MessageTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag2.setBundle("admin");
      }

      _jsp_tag2.setKey("menu.left.add.experts");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_tag3 == null) {
        _jsp_tag3 = new org.apache.struts.taglib.html.RewriteTag();
        _jsp_tag3.setPageContext(pageContext);
        _jsp_tag3.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_tag3.setPage("/user.do");
      int _jspEval12 = _jsp_tag3.doStartTag();
      int _jsp_endTagVar13 = _jsp_tag3.doEndTag();
      if (_jsp_endTagVar13 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_tag2.setKey("page.useradds.title.template.download");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_tag2.setKey("page.useradds.ins1");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      _jsp_tag3.setPage("/expertlist.xls");
      int _jspEval22 = _jsp_tag3.doStartTag();
      int _jsp_endTagVar23 = _jsp_tag3.doEndTag();
      if (_jsp_endTagVar23 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      _jsp_tag1.setKey("common.text.download");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      _jsp_tag2.setKey("page.useradds.title.expert.list");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      _jsp_tag2.setKey("page.useradds.ins2");
      _jsp_tag2.doStartTag();
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      _jsp_tag1.setKey("common.button.batch.add");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      
//*********************************
//end content
//*********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//**********************************
//footer
//**********************************

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("/inc/footer.jsp");
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      if (_jsp_tag3 != null)
        _jsp_tag3.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_useradds__jsp.java", "/conf1/admin/useradds.jsp");
    _caucho_line_map.add(14, 1);
    _caucho_line_map.add(1, 31);
    _caucho_line_map.add(6, 37);
    _caucho_line_map.add(7, 47);
    _caucho_line_map.add(8, 51);
    _caucho_line_map.add(13, 57);
    _caucho_line_map.add(19, 61);
    _caucho_line_map.add(24, 67);
    _caucho_line_map.add(27, 69);
    _caucho_line_map.add(32, 75);
    _caucho_line_map.add(33, 77);
    _caucho_line_map.add(34, 79);
    _caucho_line_map.add(39, 85);
    _caucho_line_map.add(45, 87);
    _caucho_line_map.add(46, 89);
    _caucho_line_map.add(55, 91);
    _caucho_line_map.add(63, 100);
    _caucho_line_map.add(69, 110);
    _caucho_line_map.add(73, 122);
    _caucho_line_map.add(74, 125);
    _caucho_line_map.add(74, 128);
    _caucho_line_map.add(74, 134);
    _caucho_line_map.add(79, 137);
    _caucho_line_map.add(80, 140);
    _caucho_line_map.add(93, 143);
    _caucho_line_map.add(101, 146);
    _caucho_line_map.add(106, 152);
    _caucho_line_map.add(111, 158);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/useradds.jsp"), 1184596866765L, 4084L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string15;
  private static byte []_jsp_string14;
  private static byte []_jsp_string9;
  private static byte []_jsp_string7;
  private static byte []_jsp_string1;
  private static byte []_jsp_string3;
  private static byte []_jsp_string16;
  private static byte []_jsp_string0;
  private static byte []_jsp_string8;
  private static byte []_jsp_string5;
  private static byte []_jsp_string4;
  private static byte []_jsp_string10;
  private static byte []_jsp_string12;
  private static byte []_jsp_string11;
  private static byte []_jsp_string2;
  private static byte []_jsp_string6;
  private static byte []_jsp_string13;
  static {
    try {
      _jsp_string15 = "\"> \r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </form>\r\n    </td>\r\n  </tr>\r\n</table>\r\n".getBytes("UTF8");
      _jsp_string14 = "}</td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td class=\"form_row_content\"> <div class=\"spacer_5\"></div>\r\n              <div class=\"spacer_10\"> \r\n                <input name=\"ufile\" type=\"file\" id=\"ufile\" size=\"58\">\r\n              </div></td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td nowrap class=\"form_row_submit\"><input name=\"sub\" type=\"submit\" class=\"button\" id=\"sub\" value=\"".getBytes("UTF8");
      _jsp_string9 = "</td>\r\n            <td class=\"form_row_content\">&nbsp;&nbsp;{".getBytes("UTF8");
      _jsp_string7 = "</b></td>\r\n        </tr>\r\n        <tr> \r\n          <td height=\"16\" class=\"pagecontent_right\"></td>\r\n        </tr>\r\n      </table>\r\n      <form action=\"".getBytes("UTF8");
      _jsp_string1 = "\r\n\r\n<html>\r\n".getBytes("UTF8");
      _jsp_string3 = "\r\n<table width=\"778\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"MARGIN-TOP: 10px;\">\r\n  <tr>\r\n    <td width=\"180\" height=\"55\" valign=\"top\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"leftmenu\">\r\n        <tr> \r\n          <td height=\"41\">\r\n			".getBytes("UTF8");
      _jsp_string16 = "\r\n</body>\r\n</html>".getBytes("UTF8");
      _jsp_string0 = "\r\n".getBytes("UTF8");
      _jsp_string8 = "\" method=\"post\" enctype=\"multipart/form-data\" name=\"addusers\" id=\"addusers\" onSubmit=\"return checkForm()\">\r\n        <input name=\"eventSubmit_AddUsers\" type=\"hidden\" id=\"eventSubmit_AddUsers\" value=\"1\">\r\n        <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td width=\"23%\" height=\"25\" class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string5 = "\r\n          </td>\r\n        </tr>\r\n      </table></td>\r\n    <td width=\"598\" valign=\"top\" class=\"pagecontent\">\r\n	<SCRIPT language=\"javascript\">\r\n	function checkForm()\r\n	{\r\n		if (addusers.ufile.value.length == 0) {\r\n			alert(\"".getBytes("UTF8");
      _jsp_string4 = "\r\n			".getBytes("UTF8");
      _jsp_string10 = "}{<a href=\"".getBytes("UTF8");
      _jsp_string12 = "</a>}</td>\r\n          </tr>\r\n        </table>\r\n        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"form_row\">\r\n          <tr> \r\n            <td width=\"23%\" class=\"form_row_title\">".getBytes("UTF8");
      _jsp_string11 = "\" class=\"blue\">".getBytes("UTF8");
      _jsp_string2 = "\r\n\r\n<body>\r\n".getBytes("UTF8");
      _jsp_string6 = "\");\r\n			return false;\r\n		}\r\n		return true;\r\n	}\r\n	</script>\r\n	  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <tr> \r\n          <td class=\"pagecontent_title\"><b>".getBytes("UTF8");
      _jsp_string13 = "</td>\r\n            <td class=\"form_row_content\"> &nbsp;&nbsp;{".getBytes("UTF8");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
